// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmujbfbsiqydqpktbigx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtdWpiZmJzaXF5ZHFwa3RiaWd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMzI1MDYsImV4cCI6MjA2NTgwODUwNn0.RtO_8kmAwXl-Lcs9vhJifUIUDgcN553g-W2hKLHy134";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);